# Generated by Django 5.1 on 2024-12-23 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temporary_place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.FloatField()),
                ("v", models.FloatField()),
                ("t", models.IntegerField()),
                ("total_tax", models.FloatField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="objects.objects",
                    ),
                ),
            ],
            options={
                "db_table": "Temporary_place",
                "ordering": ["total_tax"],
            },
        ),
    ]
