# Generated by Django 5.1 on 2024-12-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0001_initial"),
        ("pollutants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk_health",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concentration", models.FloatField()),
                ("sf", models.FloatField()),
                ("rfc", models.FloatField()),
                ("date", models.IntegerField()),
                ("hq", models.FloatField()),
                ("ladd", models.FloatField()),
                ("cr", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="objects.objects",
                    ),
                ),
                (
                    "pollutant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pollutants.pollutants",
                    ),
                ),
            ],
            options={
                "db_table": "Rish_health",
                "ordering": ["date"],
            },
        ),
    ]
