# Generated by Django 5.1 on 2024-12-23 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radioactive_waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_electricity', models.FloatField(max_length=100)),
                ('c1ns', models.FloatField(max_length=100)),
                ('c2ns', models.FloatField(max_length=100)),
                ('c1v', models.FloatField(max_length=100)),
                ('c2v', models.FloatField(max_length=100)),
                ('v1ns', models.FloatField(max_length=100)),
                ('v2ns', models.FloatField(max_length=100)),
                ('v1v', models.FloatField(max_length=100)),
                ('v2v', models.FloatField(max_length=100)),
                ('total_tax', models.FloatField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.objects')),
            ],
            options={
                'db_table': 'Radioactive_waste',
                'ordering': ['total_tax'],
            },
        ),
    ]
